### ISSUE TITLE
[FE] Pagination del catalogo non funzionante

### ISSUE THREAD

**Issue by Clou-dia** [teamdigitale/dati-semantic-frontend#473] opened 2024-01-21 15:21 UTC
Pagina: [Catalogo](https://schema.gov.it/search) 

L'elemento di paginazione degli elementi ricercati, quando gli elementi sono < o = a 5 (1 pagina) o anche > 5  < 10 (2 pagine) 
non segue il conto degli asset ritrovati, risulta essere fisso alle prime 3 pagine.

Esempio con elementi trovai 2 (per parola chiave "economia") (1 pagina)
Il pagination non dovrebbe comparire, invece compare con 3 pagine.

![schema gov it_search_pattern=economia](https://github.com/teamdigitale/dati-semantic-frontend/assets/98462345/3028dc68-2e18-45cf-b574-7dd3a35ddbe6)

Esempio con elementi trovati 7 (per parola chiave "istruzione") (2 pagine) 
Il pagination dovrebbe mostrare 2 pagine, invece compare con 3 pagine.

![schema gov it_search_pattern=istruzione](https://github.com/teamdigitale/dati-semantic-frontend/assets/98462345/8ca77f19-8dae-42aa-b78e-998387c613f5)

![schema gov it_search_pattern=istruzione (1)](https://github.com/teamdigitale/dati-semantic-frontend/assets/98462345/d3565fd8-fe1e-4188-91dc-b168b9e95f68)

**Comment by Francescopalermo** [comment] 2024-01-26 16:04
@Clou-dia 
Fixed pagination error in the catalog search, eliminating the option to click on non-existent pages.

**Comment by mauropratesi** [comment] 2024-01-29 15:08
CC:  @Clou-dia 
<img width="502" alt="image" src="https://github.com/teamdigitale/dati-semantic-frontend/assets/157471028/365ee0c4-f127-4887-9acb-9a0c587a5ca8">
<img width="273" alt="image" src="https://github.com/teamdigitale/dati-semantic-frontend/assets/157471028/e40cc240-62ff-40e3-bea0-8f9092c1c3f0">

The tests were conducted using the Edge and Chrome browsers on a PC (Windows) in the TEST envoronment (https://ndc-test.apps.cloudpub.testedev.istat.it/), and indeed, the issues highlighted by the reported problem has been resolved. The screenshot refers to the PC device with the Edge browser, but the same result is also observed with the Chrome browser and with the following devices: iPad Mini, iPhone SE, Samsung Galaxy S20 Ultra, Samsung Galaxy S8+.
Instead, on the following page https://schema.gov.it/search, **the error is still present**.

Tests on Safari and Brave browsers are yet to be conducted.

**Comment by Clou-dia** [comment] 2024-01-29 18:05
Adding: is it possible to center the numbers?
See as reference https://italia.github.io/bootstrap-italia/docs/componenti/paginazione/ 

<img width="492" alt="Schermata 2024-01-29 alle 19 03 27" src="https://github.com/teamdigitale/dati-semantic-frontend/assets/98462345/35df304e-80a7-4d8b-98cf-cee81b39d2fd">

**Comment by AgostinoPurificato** [comment] 2024-02-15 15:03
CC @Clou-dia 

The problem is now resolved in [dev](https://ndc-dev.apps.cloudpub.testedev.istat.it) and [test ](https://ndc-test.apps.cloudpub.testedev.istat.it) environments:
![image](https://github.com/teamdigitale/dati-semantic-frontend/assets/132351416/1170a494-f5b8-4555-ba25-63e4b61c6ec9)
![image](https://github.com/teamdigitale/dati-semantic-frontend/assets/132351416/ef0eda41-8bab-49da-94ee-836851548a69)

@Francescopalermo I linked to this issue the #475 PR, feel free to change it if it's not correct.

**Closed** 2024-02-15 18:06 UTC
Labels: bug, ux/ui
